### ISSUE TITLE
KeyError: 'srl_sp_prf_f'

### ISSUE THREAD

**Issue by chaojiang06** [jzbjyb/SpanRel#1]
Hi Zhengbao,

Thank you for providing the code. I am trying to run the code on the SRL task on the CoNLL 2012 tasks. I followed the instructions and encounter an  error like this:

> Traceback (most recent call last):
>   File "/home/chao/anaconda3/envs/spanrel/bin/allennlp", line 8, in <module>
>     sys.exit(run())
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
>     main(prog="allennlp")
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
>     args.func(args)
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/commands/train.py", line 116, in train_model_from_args
>     args.cache_prefix)
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/commands/train.py", line 160, in train_model_from_file
>     cache_directory, cache_prefix)
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/commands/train.py", line 243, in train_model
>     metrics = trainer.train()
>   File "/home/chao/anaconda3/envs/spanrel/lib/python3.6/site-packages/allennlp/training/trainer.py", line 497, in train
>     this_epoch_val_metric = val_metrics[self._validation_metric]
> KeyError: 'srl_sp_prf_f'

I try to search `srl_sp_prf_f` related code but didn't find anything. I was thinking is it possible a metric file was missing in the `/brat_multitask/metrics/` folder? Any help will be appreciated!

Thank you!

Best, 
Chao

**Comment by jzbjyb** [comment]
Hi Chao,

Thanks for your question! Which version of `allennlp` are you using? In my case, once I get the data preprocessed, I am able to run the command `./run_by_config_bert.sh $task bert-base-uncased output` without this exception.

**Comment by chaojiang06** [comment]
Hi Zhengbao,

Thank you for your response! I try to re-process the data with another script from the CoNLL 2012 website, and the problem got solved.

Thank you again!
