### ISSUE TITLE
Missing data `wlp`

### ISSUE THREAD

**Issue by SivilTaram** [jzbjyb/SpanRel#2]
Hi Zhengbao, thanks for open-sourcing the code and the detailed instructions for processing data! It seems the `wlp` data is missing in the repo (without any link or folder). Is it as expected? Many thanks :)

**Comment by SivilTaram** [comment]
For anyone who has the same question here: I found the open-source version of WLP dataset at https://github.com/chaitanya2334/WLP-Dataset, and the format is compatible, which means that you could directly use it as **a post-processed dataset**.

**Comment by jzbjyb** [comment]
Thanks for the question and sorry for the late reply! I uploaded the [script](https://github.com/neulab/cmu-multinlp/blob/master/data/wlp/run.sh) for downloading the `wlp` dataset, which did exactly the same thing as yours that clones the `WLP-Dataset` repository.

**Comment by SivilTaram** [comment]
@jzbjyb thanks for the confirmation!
